import{a as v,S as b,i as l}from"./assets/vendor-DqjOl-58.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const w="49622703-1639e63074f827bd1b79f059d",S="https://pixabay.com/api/";async function q(t,r=1){try{return(await v.get(`${S}`,{params:{key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}catch(s){throw console.error("Error fetching images:",s),s}}const d=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more");let $=new b(".gallery a");function B(t){const r=t.map(({webformatURL:s,largeImageURL:i,tags:e,likes:o,views:n,comments:h,downloads:L})=>`
      <a href="${i}" class="gallery-item">
        <img src="${s}" alt="${e}" loading="lazy" />
        <div class="info">
          <p> Likes: <span class="info-value">${o}</span></p>
          <p> Views: <span class="info-value">${n}</span></p>
          <p> Comments: <span class="info-value">${h}</span></p>
          <p> Downloads: <span class="info-value">${L}</span></p>
        </div>
      </a>
    `).join("");d.innerHTML=r,$.refresh()}function E(){d.innerHTML=""}function M(){f.classList.add("visible")}function c(){f.classList.remove("visible")}function P(){m.classList.add("visible")}function p(){m.classList.remove("visible")}const H=document.querySelector(".form"),O=document.querySelector(".gallery"),x=document.querySelector(".load-more");document.querySelector(".loader");let g="",a=1,u=0;H.addEventListener("submit",async t=>{t.preventDefault();const r=t.target.elements["search-text"].value.trim();r&&(g=r,a=1,E(),p(),await y())});x.addEventListener("click",async()=>{a++,await y()});async function y(){try{M();const{hits:t,totalHits:r}=await q(g,a);if(a===1&&(u=r),t.length===0){l.warning({title:"Warning",message:"No images found!"}),c();return}B(t),t.length<15||a*15>=u?(p(),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):P(),I()}catch(t){l.error({title:"Error",message:"Failed to fetch images!"}),console.error(t)}finally{c()}}function I(){var r;const{height:t}=((r=O.firstElementChild)==null?void 0:r.getBoundingClientRect())||{height:0};window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
