import{a as v,S as b,i as c}from"./assets/vendor-DqjOl-58.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const w="49622703-1639e63074f827bd1b79f059d",S="https://pixabay.com/api/";async function $(r,o=1){try{return(await v.get(`${S}`,{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data}catch(s){throw console.error("Error fetching images:",s),s}}const d=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more");let q=new b(".gallery a");function E(r){const o=r.map(({webformatURL:s,largeImageURL:i,tags:e,likes:t,views:n,comments:h,downloads:L})=>`
      <a href="${i}" class="gallery-item">
        <img src="${s}" alt="${e}" loading="lazy" />
        <div class="info">
          <p> Likes: <span class="info-value">${t}</span></p>
          <p> Views: <span class="info-value">${n}</span></p>
          <p> Comments: <span class="info-value">${h}</span></p>
          <p> Downloads: <span class="info-value">${L}</span></p>
        </div>
      </a>
    `).join("");d.innerHTML=o,q.refresh()}function M(){d.innerHTML=""}function B(){f.classList.add("visible")}function l(){f.classList.remove("visible")}function O(){m.classList.add("visible")}function p(){m.classList.remove("visible")}const P=document.querySelector(".form"),x=document.querySelector(".load-more");let y="",a=1,u=0;P.addEventListener("submit",async r=>{r.preventDefault();const o=r.target.elements["search-text"].value.trim();o&&(y=o,a=1,M(),p(),await g())});x.addEventListener("click",async()=>{a++,await g()});async function g(){try{B();const{hits:r,totalHits:o}=await $(y,a);if(a===1&&(u=o),r.length===0){c.warning({title:"Warning",message:"No images found!"}),l();return}E(r),a*15>=u?(p(),c.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):O()}catch(r){c.error({title:"Error",message:"Failed to fetch images!"}),console.error(r)}finally{l()}}
//# sourceMappingURL=index.js.map
